### ISSUE TITLE
null is treated as a variable

### ISSUE THREAD

**Issue by pSub** [red6/dmn-check#7]
Currently the special value `null` is treated as a variable and not as the special value `null`. This causes wrong shadowing warnings. This issue was brought up by @davidibl in issue #6.

**Comment by pSub** [comment]
Fixed in 4f36c4aa9a2608ba8a91eeda5dd80116db428a3c.

**Comment by davidibl** [comment]
@pSub 
Is there a release containing this fox already planned?

Kind regards

**Comment by pSub** [comment]
Hey @davidibl I'll try to prepare a new 1.1.x release later containing this fix today or tomorrow.

**Comment by pSub** [comment]
The fix is contained in release 1.1.4, which should be available on Maven central shortly.
