### ISSUE TITLE
outputEntryTypeValidator error

### ISSUE THREAD

**Issue by kishorehs123** [red6/dmn-check#87]
Hi All,

We have created DMN with Output value type is Integer and we try to pass negative value like  -1 then we getting  error message "Operator is not supported in UnaryExpression"

Please find the document of  DMN used for validation.

[New Microsoft Word Document.docx](https://github.com/red6/dmn-check/files/8379309/New.Microsoft.Word.Document.docx)

Please help me to resolve issue.

**Comment by pSub** [comment]
Should be fixed in release 1.2.2.

**Comment by pSub** [comment]
… and thank you for reporting this bug! Much appreciated :heart:

**Comment by pSub** [comment]
… and maybe don't attach a docx file next time. It looks a bit fishy. I mean, like some really sophisticated phising attempt.
