### ISSUE TITLE
Issue while parsing DMN with Javascript

### ISSUE THREAD

**Issue by nairagit** [red6/dmn-check#88]
Hi,

I have a DMN with the expression language as JavaScript.
When I run it against the DMN-Check utility I get an error -  Could not parse 'ToPostalCode.contains('BT')': line 1, column 22:

Could you please help on this ?
Attached the DMN screenshot for reference

<img width="758" alt="image" src="https://user-images.githubusercontent.com/102733487/161040834-2c0c3d36-d576-408e-b751-669daa4c205e.png">

**Comment by pSub** [comment]
Currently, `dmn-check` supports FEEL as the only expression language and just assumes that everything is FEEL. Issue #83 describes this behavior. I will try to implement #83 in the next couple days. When #83 is implemented `dmn-check` will not attempt  analysis on any other expression language than FEEL. Support for other expressions languages, such as Javascript, is planed but without any concret timeline.

**Comment by pSub** [comment]
@nairagit: I have pushed a fix for your problem in PR #98. It would be great if you could give it a try. If it works for you, I will create a bugfix release of `dmn-check`.

**Comment by pSub** [comment]
Hi @nairagit, thanks for testing the patch. It seems to work as expected. Just in case this wasn't explicit: `dmn-check` does parse and analyse DMNs containing javascript as expression language. However, it will do expression language specific analysis currently only for FEEL. It tries to be as precise as possible in detecting which expression language is used in which part of your DMN model.

As I said, support for javascript is on the roadmap, but it seems to be quite a lot of work.

I will release a bugfix version of `dmn-check` including #98.

**Comment by pSub** [comment]
I have released version 1.2.3 which should be available on Maven central within the next couple of hours.
